---
heat_template_version: 2015-04-30

description: "Server with loadbalancing pool member"


parameters:
##################################
# Server
##################################
  server_base_name:
    type: string
    label: "Server base name"
    description: "Base name to the new server"
    default: "my_server"

  server_key_name:
    type: string
    label: "Server key name"
    description: "Server key name."
    default: "my_key"

  server_image:
    type: string
    label: "Server image"
    description: "The image to use for the new server instance."
    default: "CentOS-7.3"

  server_flavor:
    type: string
    label: "Server flavor (size)"
    description: "The flavor of the new server instance."
    constraints:
      - description: "Value must be one of: m1.tiny, m1.small ..."
        allowed_values:
          - m1.tiny
          - m1.small
          - m1.medium
          - m1.large
          - r1.large
          - r1.xlarge
          - m1.xlarge
          - m1.2xlarge
          - r1.2xlarge
          - r1.3xlarge
          - r1.4xlarge
    default: "m1.medium"

  server_volume_name:
    type: string
    label: "Server volume name"
    description: "The server volume name"
    default: "my_server_volume"

  server_volume_size:
    type: number
    label: "Size of the server volume (in GB)"
    description: "The size of the new volume in GB"
    default: 10

  server_volume_delete_on_termination:
    type: boolean
    label: "Should delete volume when server is terminated ?"
    description: "Boolean to decide if volume will be deleted when server is terminated"
    default: true

  server_affinity_group:
    type: string
    label: "Server affinity group"
    description: "The name/id of the server affinity group"

#####################################
# Networks
#####################################
  private_network:
    type: string
    label: "Private network"
    description: "Private network for server."
    default: "my_private_network"

  private_sub_network:
    type: string
    label: "Private sub network"
    description: "Private sub network fro server."
    default: "my_private_sub_network"

#####################################
# Load balancer
#####################################
  loadbalancer_pool:
   type: string
   label: "Loadbalancer pool"
   description: "Loadbalancer pool"

resources:
  server:
    type: "OS::Nova::Server::PocServer"
    properties:
      server_base_name: {get_param: server_base_name}
      server_key_name: {get_param: server_key_name}
      server_image: {get_param: server_image}
      server_flavor: {get_param: server_flavor}
      server_volume_name: {get_param: server_volume_name}
      server_volume_size: {get_param: server_volume_size}
      server_volume_delete_on_termination: {get_param: server_volume_delete_on_termination}
      server_affinity_group: {get_param: server_affinity_group}
      private_network: {get_param: private_network}

  server_pool:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      address: {get_attr: [server, server_private_ip]}
      pool: {get_param: loadbalancer_pool}
      protocol_port: 80
      subnet: {get_param: private_sub_network}
    depends_on: server

